# Generated by Django 3.2.6 on 2021-08-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_classroom_course_department'),
        ('student', '0002_auto_20210829_0601'),
        ('academic', '0002_generalsequence_report_card_result_sequence_teachersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersequence',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.course'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='report_card',
            name='results',
            field=models.ManyToManyField(blank=True, to='academic.Result'),
        ),
        migrations.AddField(
            model_name='generalsequence',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.classroom'),
        ),
    ]
