# Generated by Django 3.2.6 on 2021-08-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, null=True)),
                ('sequence', models.CharField(max_length=100, null=True)),
                ('hours_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='remark',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
