# Generated by Django 3.2.6 on 2021-09-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_classroom_headmaster'),
        ('academic', '0005_auto_20210830_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAbsentHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('sequence', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.classroom')),
            ],
        ),
    ]
