# Generated by Django 3.2.6 on 2021-09-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_generalabsenthours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalabsenthours',
            old_name='academic_year',
            new_name='year',
        ),
    ]
