# Generated by Django 3.2.6 on 2021-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_absenthours_hours_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenthours',
            name='consignes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='absenthours',
            name='exclusions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
