# Generated by Django 3.2.6 on 2021-09-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_displinarycouncil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisplinaryCouncil',
            new_name='DisciplinaryCouncil',
        ),
    ]
