# Generated by Django 3.2.6 on 2021-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_rename_displinarycouncil_disciplinarycouncil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absenthours',
            old_name='exclusions',
            new_name='hr_exclusions',
        ),
        migrations.AddField(
            model_name='absenthours',
            name='jr_exclusions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
