# Generated by Django 3.2.6 on 2021-09-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_auto_20210903_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.ManyToManyField(blank=True, to='academic.Report_card')),
            ],
        ),
    ]
