# Generated by Django 3.2.6 on 2021-09-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_student_semester_reportcard'),
        ('academic', '0014_semesterreportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='mark2',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='SemesterReportCard',
        ),
    ]
