# Generated by Django 3.2.6 on 2021-09-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_result_sequence2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='mark2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=4, null=True),
        ),
    ]
