# Generated by Django 3.2.6 on 2021-09-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_result_average2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='average2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='mark2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
