# Generated by Django 3.2.6 on 2021-09-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_auto_20210905_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('conclusion', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
