# Generated by Django 3.2.6 on 2021-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0026_classcouncil_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcouncil',
            name='average2',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
