# Generated by Django 3.2.6 on 2021-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_classcouncil_average2'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcouncil',
            name='hours2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
