# Generated by Django 3.2.6 on 2021-09-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_classcouncil_hours2'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_card',
            name='sem_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
