# Generated by Django 3.2.6 on 2021-09-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_department_group_type'),
        ('academic', '0029_report_card_sem_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_card',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.classroom'),
        ),
    ]
