# Generated by Django 3.2.6 on 2021-09-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_auto_20210906_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinarycouncil',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='disciplinarycouncil',
            name='year',
        ),
        migrations.AddField(
            model_name='disciplinarycouncil',
            name='average',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='disciplinarycouncil',
            name='average2',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='disciplinarycouncil',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinarycouncil',
            name='hours2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinarycouncil',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
