# Generated by Django 3.2.6 on 2021-09-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0032_auto_20210907_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinarycouncil',
            old_name='average',
            new_name='ex_days',
        ),
        migrations.RenameField(
            model_name='disciplinarycouncil',
            old_name='average2',
            new_name='ex_hours',
        ),
    ]
