# Generated by Django 3.2.6 on 2021-09-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0033_auto_20210907_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ex_days', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('hours2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExclusionHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ex_hours', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('hours2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplinarycouncil',
            name='ex_days',
        ),
        migrations.RemoveField(
            model_name='disciplinarycouncil',
            name='ex_hours',
        ),
    ]
