# Generated by Django 3.2.6 on 2021-09-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0034_auto_20210907_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
