# Generated by Django 3.2.6 on 2021-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_auto_20210907_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersequence',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
