# Generated by Django 3.2.6 on 2021-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_auto_20210908_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenthours',
            name='convocation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='absenthours',
            name='def_exclusion',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
