# Generated by Django 3.2.6 on 2021-09-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0040_card_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonourRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('average', models.CharField(blank=True, max_length=100, null=True)),
                ('class_average', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(max_length=100, null=True)),
                ('encouragement', models.BooleanField(default=False, null=True)),
                ('congrats', models.BooleanField(default=False, null=True)),
                ('sequence', models.CharField(max_length=100, null=True)),
                ('classroom', models.CharField(max_length=100, null=True)),
                ('main_teacher', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
