# Generated by Django 3.2.6 on 2021-09-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_cards'),
        ('academic', '0041_honourroll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HonourRoll',
            new_name='HonorRoll',
        ),
    ]
