# Generated by Django 3.2.6 on 2021-09-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0043_alter_honorroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorroll',
            name='stud_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
