# Generated by Django 3.1.7 on 2021-08-17 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=45)),
                ('nationality', models.CharField(choices=[('Afrique du Sud', 'Afrique du Sud'), ('Algérie', 'Algérie'), ('Angola', 'Angola'), ('Bénin', 'Bénin'), ('Botswana', 'Botswana'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cameroun', 'Cameroun'), ('Cap-Vert', 'Cap-Vert'), ('République centrafricaine', 'République centrafricaine'), ('Comores', 'Comores'), ('République du Congo', 'République du Congo'), ('République démocratique du Congo', 'République démocratique du Congo'), ('Côte d’Ivoire', 'Côte d’Ivoire'), ('Djibouti', 'Djibouti'), ('Égypte', 'Égypte'), ('Érythrée', 'Érythrée'), ('Eswatini', 'Eswatini'), ('Éthiopie', 'Éthiopie'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Ghana', 'Ghana'), ('Guinée', 'Guinée'), ('Guinée-Bissau', 'Guinée-Bissau'), ('Guinée équatoriale', 'Guinée équatoriale'), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libye', 'Libye'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Maroc', 'Maroc'), ('Maurice', 'Maurice'), ('Mauritanie', 'Mauritanie'), ('Mozambique', 'Mozambique'), ('Naminie', 'Namibie'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Ouganda', 'Ouganda'), ('Rwanda', 'Rwanda'), ('São Tomé-et-Principe', 'São Tomé-et-Principe'), ('Sénégal', 'Sénégal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Somalie', 'Somalie'), ('Soudan', 'Soudan'), ('Soudan du Sud', 'Soudan du Sud'), ('Tanzanie', 'Tanzanie'), ('Tchad', 'Tchad'), ('Togo', 'Togo'), ('Tunisie', 'Tunisie'), ('Zambie', 'Zambie'), ('Zimbabwe', 'Zimbabwe')], default='Cameroun', max_length=45)),
                ('religion', models.CharField(choices=[('christianisme', 'christianisme'), ('islam', 'islam')], default='christianisme', max_length=45)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('single', 'Single')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('academic_year', models.CharField(blank=True, choices=[('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=50, null=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=45)),
                ('nationality', models.CharField(choices=[('Afrique du Sud', 'Afrique du Sud'), ('Algérie', 'Algérie'), ('Angola', 'Angola'), ('Bénin', 'Bénin'), ('Botswana', 'Botswana'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cameroun', 'Cameroun'), ('Cap-Vert', 'Cap-Vert'), ('République centrafricaine', 'République centrafricaine'), ('Comores', 'Comores'), ('République du Congo', 'République du Congo'), ('République démocratique du Congo', 'République démocratique du Congo'), ('Côte d’Ivoire', 'Côte d’Ivoire'), ('Djibouti', 'Djibouti'), ('Égypte', 'Égypte'), ('Érythrée', 'Érythrée'), ('Eswatini', 'Eswatini'), ('Éthiopie', 'Éthiopie'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Ghana', 'Ghana'), ('Guinée', 'Guinée'), ('Guinée-Bissau', 'Guinée-Bissau'), ('Guinée équatoriale', 'Guinée équatoriale'), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libye', 'Libye'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Maroc', 'Maroc'), ('Maurice', 'Maurice'), ('Mauritanie', 'Mauritanie'), ('Mozambique', 'Mozambique'), ('Naminie', 'Namibie'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Ouganda', 'Ouganda'), ('Rwanda', 'Rwanda'), ('São Tomé-et-Principe', 'São Tomé-et-Principe'), ('Sénégal', 'Sénégal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Somalie', 'Somalie'), ('Soudan', 'Soudan'), ('Soudan du Sud', 'Soudan du Sud'), ('Tanzanie', 'Tanzanie'), ('Tchad', 'Tchad'), ('Togo', 'Togo'), ('Tunisie', 'Tunisie'), ('Zambie', 'Zambie'), ('Zimbabwe', 'Zimbabwe')], default='Cameroun', max_length=45)),
                ('religion', models.CharField(choices=[('christianisme', 'christianisme'), ('islam', 'islam')], default='christianisme', max_length=45)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_no', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('academic_year', models.CharField(blank=True, choices=[('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=50, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_authorized', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
