# Generated by Django 3.2.6 on 2021-08-29 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20210829_0601'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('academic', '0003_auto_20210829_0601'),
        ('accounts', '0002_auto_20210829_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(blank=True, to='administration.Department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sequence',
            field=models.ManyToManyField(to='academic.TeacherSequence'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('masculin', 'masculin'), ('feminin', 'feminin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_authorized',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
