# Generated by Django 3.2.6 on 2021-09-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_classroom_headmaster'),
        ('accounts', '0003_auto_20210829_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='administration.Classroom'),
        ),
    ]
