# Generated by Django 3.2.6 on 2021-08-29 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studies_type', models.CharField(choices=[('Generale', 'Generale'), ('Technique', 'Technique')], max_length=100)),
                ('group_type', models.CharField(choices=[('science', 'science'), ('literaire', 'literaire'), ('mechanique', 'mechanique'), ('maconerie', 'maconerie'), ('generale', 'generale')], max_length=100)),
                ('section', models.CharField(choices=[('anglophone', 'anglophone'), ('francophone', 'francophone')], max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('main_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('anglophone', 'anglophone'), ('francophone', 'francophone')], max_length=100)),
                ('studies_type', models.CharField(choices=[('Generale', 'Generale'), ('Technique', 'Technique')], max_length=100)),
                ('group_type', models.CharField(choices=[('science', 'science'), ('literaire', 'literaire'), ('mechanique', 'mechanique'), ('maconerie', 'maconerie')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coeff', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.classroom')),
                ('department', models.ManyToManyField(to='administration.Department')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
