# Generated by Django 3.2.6 on 2021-08-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_classroom_course_department'),
        ('time_table', '0002_auto_20210829_0601'),
        ('student', '0002_auto_20210829_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_table.room'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
