# Generated by Django 3.2.6 on 2021-09-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20210829_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='headmaster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
