# Generated by Django 3.2.6 on 2021-09-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_classroom_headmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='headmaster',
        ),
    ]
