# Generated by Django 3.2.6 on 2021-09-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_classroom_headmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='group_type',
            field=models.CharField(choices=[('science', 'science'), ('literaire', 'literaire'), ('mechanique', 'mechanique'), ('maconerie', 'maconerie'), ('generale', 'generale')], max_length=100),
        ),
    ]
