# Generated by Django 3.1.7 on 2021-08-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_of_birth', models.CharField(max_length=20)),
                ('place_of_birth', models.CharField(max_length=45)),
                ('nationality', models.CharField(choices=[('Afrique du Sud', 'Afrique du Sud'), ('Algérie', 'Algérie'), ('Angola', 'Angola'), ('Bénin', 'Bénin'), ('Botswana', 'Botswana'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cameroun', 'Cameroun'), ('Cap-Vert', 'Cap-Vert'), ('République centrafricaine', 'République centrafricaine'), ('Comores', 'Comores'), ('République du Congo', 'République du Congo'), ('République démocratique du Congo', 'République démocratique du Congo'), ('Côte d’Ivoire', 'Côte d’Ivoire'), ('Djibouti', 'Djibouti'), ('Égypte', 'Égypte'), ('Érythrée', 'Érythrée'), ('Eswatini', 'Eswatini'), ('Éthiopie', 'Éthiopie'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Ghana', 'Ghana'), ('Guinée', 'Guinée'), ('Guinée-Bissau', 'Guinée-Bissau'), ('Guinée équatoriale', 'Guinée équatoriale'), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libye', 'Libye'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Maroc', 'Maroc'), ('Maurice', 'Maurice'), ('Mauritanie', 'Mauritanie'), ('Mozambique', 'Mozambique'), ('Naminie', 'Namibie'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Ouganda', 'Ouganda'), ('Rwanda', 'Rwanda'), ('São Tomé-et-Principe', 'São Tomé-et-Principe'), ('Sénégal', 'Sénégal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Somalie', 'Somalie'), ('Soudan', 'Soudan'), ('Soudan du Sud', 'Soudan du Sud'), ('Tanzanie', 'Tanzanie'), ('Tchad', 'Tchad'), ('Togo', 'Togo'), ('Tunisie', 'Tunisie'), ('Zambie', 'Zambie'), ('Zimbabwe', 'Zimbabwe')], default='Cameroun', max_length=45)),
                ('religion', models.CharField(choices=[('christianisme', 'christianisme'), ('islam', 'islam')], default='christianisme', max_length=45)),
                ('gender', models.CharField(choices=[('masculin', 'masculin'), ('feminin', 'feminin')], max_length=10)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('academic_year', models.CharField(blank=True, choices=[('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=50, null=True)),
                ('is_delete', models.BooleanField(default=False, null=True)),
                ('parent_address', models.CharField(max_length=100, null=True)),
                ('parent_name', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
