# Generated by Django 3.2.6 on 2021-08-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20210829_0601'),
        ('student', '0002_auto_20210829_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.ManyToManyField(to='academic.Date'),
        ),
    ]
