# Generated by Django 3.2.6 on 2021-08-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210830_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Nouveau', 'Nouveau'), ('Ancien', 'Ancien')], max_length=10, null=True),
        ),
    ]
