# Generated by Django 3.2.6 on 2021-08-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Nouveau', 'Nouveau'), ('Ancien', 'Ancien')], default='Nouveau', max_length=10, null=True),
        ),
    ]
