# Generated by Django 3.2.6 on 2021-08-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remark'),
        ('student', '0006_auto_20210830_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remark',
            field=models.ManyToManyField(to='academic.Remark'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_of_origin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
