# Generated by Django 3.2.6 on 2021-08-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20210830_0809'),
        ('student', '0007_auto_20210830_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absent_hours',
            field=models.ManyToManyField(to='academic.AbsentHours'),
        ),
    ]
