# Generated by Django 3.2.6 on 2021-08-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20210830_0809'),
        ('student', '0008_student_absent_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ManyToManyField(blank=True, to='academic.Date'),
        ),
    ]
