# Generated by Django 3.2.6 on 2021-08-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20210830_0809'),
        ('student', '0009_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='absent_hours',
            field=models.ManyToManyField(blank=True, to='academic.AbsentHours'),
        ),
        migrations.AlterField(
            model_name='student',
            name='remark',
            field=models.ManyToManyField(blank=True, to='academic.Remark'),
        ),
    ]
