# Generated by Django 3.2.6 on 2021-09-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_semester_reportcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester_reportcard',
        ),
    ]
