# Generated by Django 3.2.6 on 2021-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_student_semester_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='locality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
