# Generated by Django 3.2.6 on 2021-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0039_card'),
        ('student', '0013_auto_20210908_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cards',
            field=models.ManyToManyField(to='academic.Card'),
        ),
    ]
