# Generated by Django 3.2.6 on 2021-09-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0042_rename_honourroll_honorroll'),
        ('student', '0014_student_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='honor_rolls',
            field=models.ManyToManyField(to='academic.HonorRoll'),
        ),
    ]
